version: '3'
services:
  db:
    image: postgres:latest
    container_name: 'test-db'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5441:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data/


  redis:
    image: "redis:alpine"
    container_name: 'redis-test-container'
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
